// Impor tipe Metadata dari Next.js untuk mendefinisikan metadata halaman
import type { Metadata } from "next";
// Impor font Geist dan Geist_Mono dari next/font/google
import { Geist, Geist_Mono } from "next/font/google";
// Impor file CSS global
import "./globals.css";
// Impor komponen Navbar
import Navbar from "@/components/navbar";

// Inisialisasi font Geist Sans dengan variabel CSS dan subset latin
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Inisialisasi font Geist Mono dengan variabel CSS dan subset latin
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Definisikan metadata untuk aplikasi
export const metadata: Metadata = {
  title: "Create Next App", // Judul default untuk halaman
  description: "Generated by create next app", // Deskripsi default
};

// Definisikan komponen RootLayout sebagai layout utama aplikasi
export default function RootLayout({
  children, // children akan berisi konten halaman yang aktif
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // elemen html dengan atribut bahasa inggris
    <html lang="en">
      {/* elemen body dengan kelas font dari Geist dan anti-aliasing */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render komponen Navbar di setiap halaman */}
        <Navbar />
        {/* Kontainer utama untuk konten halaman */}
        <main>{children}</main>
      </body>
    </html>
  );
}
